In [ ]:
#Use markdown formatting for the following questions:

##1. What does Pandas stand for?
###Pandas stands for either "Panel Data" or "Python Analysis Library".

##2. What are 2 collections used in Pandas?
###Series and DataFrames

##3. Name 4 things Pandas can do for us.
###Pandas can read data from a variety of sources, it can manipulate data, it can visualize data, and it can analyze data.

##4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
###One should use the inplace keyword.

##5. What is a CSV?
###A CSV is a comma separated values file. It is a plain text file that stores tabular data.

##6. When cleaning data what values do we not like in our data?
###We do not like null values in our data.

In [4]:
#7.Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

array = np.arange(12).reshape(2,3,2)
print(array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [10]:
#8.Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

array2 = np.linspace(0,20,6)
print(array2)

[ 0.  4.  8. 12. 16. 20.]


In [15]:
#9.Make a Deep Copy of the above array

import copy

array_copy = copy.deepcopy(array2)
print(array_copy)

[ 0.  4.  8. 12. 16. 20.]


In [16]:
#10.Concatenate these 3 arrays into a new array named 'newArray'...

array1 = ([[25, 16]])
array2 = ([[11, 2], [13, 4]])
array3 = ([[7, 81], [5, 6], [11, 12]])


newArray = np.concatenate((array1, array2, array3))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [17]:
#11.Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [12]:
#12.Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

var1,var2= array

print(var1)
print(var2)




[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [9]:
#13.Combined and sort the following arrays into one called 'comboArray' ...

Aa = ([10, 11, 12, 13, 14, 15, 16, 17])
Bb = ([20, 21, 22, 23, 24, 25, 26, 27])
Cc = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((Aa, Bb, Cc))
comboArray = np.sort(comboArray)
print(comboArray)

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]


In [15]:
#14.Take 'comboArray' and perform the following slicing activities:

#print sec1 - the 2nd element
#print sec2 - all elements from the 3rd element to the last
#print sec3 - all elements from the 4th to the 14th elements
#print sec4 - the last 6 elements
#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
#print sec6 - from #20 every even element to the end
#print sec7 - from the last element moving forward, every 5th element.

print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:14])
print(comboArray[-6:])
print(comboArray[-24:-10])
print(comboArray[20::2])
print(comboArray[-1::-5])



1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[24 26]
[27 22 15 10  3]


In [7]:
#15.Using Series, create a DataFrame that looks like this:

import pandas as pd

ingredients = pd.Series (['Flour', 'Milk', 'Eggs', 'Spam'])
quantity = pd.Series ([4, 1, 2, 1])
unit = (['Cups', 'Cup', 'Large', 'Can'])

Dinner_DataFrame = pd.DataFrame({'Ingredients': ingredients, 'Quantity': quantity, 'Unit': unit})
print(DinnerDataFrame)



  Ingredients  Quantity   Unit
0       Flour         4   Cups
1        Milk         1    Cup
2        Eggs         2  Large
3        Spam         1    Can


In [9]:
#16 Take this data and creat a DataFrame named studentData

data = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket


In [14]:
#17.Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData = pd.DataFrame(data)

studentData['Deserts'] = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
print(studentData)


      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   

        Deserts  
0     ice cream  
1  Cashew Fudge  
2       waffels  
3  Carrot Halwa  


In [15]:
#18.Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_Values(by= ['Name', 'address'], ascending=True)
print(studentData)

AttributeError: 'DataFrame' object has no attribute 'sort_Values'

In [16]:
#19.Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')
animals = pd.read_csv('cows_and_goats.csv')
print(animals)



  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19


In [27]:
#(A) Using Pandas, make your own .CSV file with data on vegetables and save it.
# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

Taylor_Swift = pd.DataFrame({'Album': ['Taylor Swift', 'Fearless', 'Speak Now']})
Taylor_Swift.to_csv('Taylor_Swift.csv')
Taylor_Swift = pd.read_csv('Taylor_Swift.csv')
print(Taylor_Swift)

print('\n')

df['Taylor_Swift'] = ['Folklore', 'Evermore', 'Midnights']
df.to_csv('Taylor_Swift.csv', index=False)
update_df = pd.read_csv('Taylor_Swift.csv')
print(update_df)

   Unnamed: 0         Album
0           0  Taylor Swift
1           1      Fearless
2           2     Speak Now




ValueError: Length of values (3) does not match length of index (2)