In [ ]:
#Use markdown formatting for the following questions:

##1. What does Pandas stand for?
###Pandas stands for either "Panel Data" or "Python Analysis Library".

##2. What are 2 collections used in Pandas?
###Series and DataFrames

##3. Name 4 things Pandas can do for us.
###Pandas can read data from a variety of sources, it can manipulate data, it can visualize data, and it can analyze data.

In [1]:
#7.Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

array = np.arange([1,2,3(4,5,6)]).reshape(2,3,2)
print(array)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [10]:
#8.Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

array2 = np.linspace(0,20,6)
print(array2)

[ 0.  4.  8. 12. 16. 20.]


In [15]:
#9.Make a Deep Copy of the above array

import copy

array_copy = copy.deepcopy(array2)
print(array_copy)

[ 0.  4.  8. 12. 16. 20.]


In [16]:
#10.Concatenate these 3 arrays into a new array named 'newArray'...

array1 = ([[25, 16]])
array2 = ([[11, 2], [13, 4]])
array3 = ([[7, 81], [5, 6], [11, 12]])


newArray = np.concatenate((array1, array2, array3))
print(newArray)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [17]:
#11.Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [ ]:
#12.Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.



In [ ]:
#13.Combined and sort the following arrays into one called 'comboArray' ...

    one = ([10, 11, 12, 13, 14, 15, 16, 17])
    two = ([20, 21, 22, 23, 24, 25, 26, 27])
    three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#14.Take 'comboArray' and perform the following slicing activities:

print sec1 - the 2nd element
print sec2 - all elements from the 3rd element to the last
print sec3 - all elements from the 4th to the 14th elements
print sec4 - the last 6 elements
print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print sec6 - from #20 every even element to the end
print sec7 - from the last element moving forward, every 5th element.

In [ ]:
#15.Using Series, create a DataFrame that looks like this: